### ISSUE TITLE
Question: What pm_type mptcpd has?

### ISSUE THREAD

**Issue by svkim** [multipath-tcp/mptcpd#287]
Hello, MPTCP developer.

I'm a newbie to understand MPTCP daemon.
Can I ask for one question?

What pm_type this mptcpd has?
Kernel type? or UserSpace type?

I'd like to know it.

Thanks,
Seongsik Kim.

**Comment by matttbe** [comment]
Hello

Just to be sure, are you talking about the [sysctl knob](https://docs.kernel.org/networking/mptcp-sysctl.html): `net.mptcp.pm_type`?

If yes, mptcpd can work with both, it depends on which path manager plugin you use, e.g. `add-adv` will setup the in-kernel path manager, while `sspi` will require the userspace PM.

The in-kernel PM can also be configured with `ip` and recent versions of Network-Manager.

Does it reply to your question?

**Comment by sxkim** [comment]
Thank you matttbe,

> are you talking about the [sysctl knob](https://docs.kernel.org/networking/mptcp-sysctl.html): net.mptcp.pm_type?

Yes. 

Actually, I would like to know if `upstream_add_subflow` function can be used in Userspace PM.

https://github.com/multipath-tcp/mptcpd/blob/7fb64162e167ae6822bd2f7e88daa59829eebcce/src/netlink_pm_upstream.c#L339


Can `upstream_add_subflow` function be used in Userspace PM?

Thanks.

**Comment by matttbe** [comment]
> Can `upstream_add_subflow` function be used in Userspace PM?

Yes it can. All functions taking a `token` are for the userspace PM because they do something per connection.

Please note that you are supposed to use public functions, see the [doc](https://mptcpd.mptcp.dev/doc/html/include_2mptcpd_2path__manager_8h.html), e.g. [`mptcpd_pm_add_subflow()`](https://mptcpd.mptcp.dev/doc/html/include_2mptcpd_2path__manager_8h.html#af6db7bae0caab2fc4e6f5b620dde79d2) in this case, instead of `upstream_add_subflow()`.

**Comment by matttbe** [comment]
I guess I replied to the original question, I can then close the ticket.

If not, feel free to continue the discussion here.

**Comment by svkim** [comment]
Thank you matttbe.
